# File: azure-pipelines.yml
# Date: 12-Sep-2021 jdw Created pipeline
#
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - master

pr:
  - master

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-template-tox-job.yml
    parameters: { tox: "format_pep8", python: "3.10", os: "linux" }
  - template: azure-template-tox-job.yml
    parameters: { tox: "lint_pylint", python: "3.10", os: "linux" }
  - template: azure-template-tox-job.yml
    parameters: { tox: "test_coverage", python: "3.10", os: "linux" }
    #
  - template: azure-template-tox-job.yml
    parameters: { tox: "py310", python: "3.10", os: "linux" }
  #
  - template: azure-template-tox-job.yml
    parameters: { tox: "py310", python: "3.10", os: "macos" }
  #
  - template: azure-template-publish-job.yml
    parameters: { tox: "py310", python: "3.10", os: "linux" }
  #
